services:
  hy3d:
    build: .
    container_name: hy3d
    user: "${UID}:${GID}"
    network_mode: host
    volumes:
      - ./Hunyuan3D-2.1-DGX:/workspace/Hunyuan3D-2.1-DGX
      - ./hy3dpaint/ckpt:/workspace/Hunyuan3D-2.1-DGX/hy3dpaint/ckpt
      - ./hf_cache:/workspace/cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility

      HF_HOME: /workspace/cache/huggingface
      HTTP_PROXY: http://127.0.0.1:10808/
      HTTPS_PROXY: http://127.0.0.1:10808/
      http_proxy: http://127.0.0.1:10808/
      https_proxy: http://127.0.0.1:10808/
      NO_PROXY: localhost,127.0.0.0/8,::1
      no_proxy: localhost,127.0.0.0/8,::1
    env_file:
      - .env
    working_dir: /workspace/Hunyuan3D-2.1-DGX
    tty: true
    stdin_open: true
